const std = @import("std");
const schema = @import("./schema.zig");

pub const Type = enum {
    ready,
    resumed,
    guild_create,
    guild_update,
    guild_delete,
    channel_create,
    channel_update,
    channel_delete,
    channel_pins_update,
    message_create,
    message_update,
    message_delete,
    message_delete_bulk,
    message_poll_vote_add,
    message_poll_vote_remove,
    guild_member_add,
    guild_member_update,
    guild_member_remove,
    guild_members_chunk,
    message_reaction_add,
    message_reaction_remove,
    message_reaction_remove_all,
    message_reaction_remove_emoji,
    interaction_create,
    user_update,
    presence_update,
    typing_start,
    voice_state_update,
    voice_server_update,
    voice_channel_effect_send,
    webhooks_update,
    invite_create,
    invite_delete,
    guild_ban_add,
    guild_ban_remove,
    guild_role_create,
    guild_role_update,
    guild_role_delete,
    guild_emojis_update,
    guild_stickers_update,
    guild_integrations_update,
    guild_audit_log_entry_create,
    auto_moderation_rule_create,
    auto_moderation_rule_update,
    auto_moderation_rule_delete,
    auto_moderation_action_execution,
    application_command_permissions_update,
    entitlement_create,
    entitlement_update,
    entitlement_delete,
    subscription_create,
    subscription_update,
    subscription_delete,
    guild_scheduled_event_create,
    guild_scheduled_event_update,
    guild_scheduled_event_delete,
    guild_scheduled_event_user_add,
    guild_scheduled_event_user_remove,
    guild_soundboard_sound_create,
    guild_soundboard_sound_update,
    guild_soundboard_sound_delete,
    guild_soundboard_sounds_update,
    stage_instance_create,
    stage_instance_update,
    stage_instance_delete,
    thread_create,
    thread_update,
    thread_delete,
    thread_list_sync,
    thread_members_update,
    thread_member_update,
    unknown,
};

pub const Events = enum {
    ClientReady,
    Resumed,
    GuildCreate,
    GuildUpdate,
    GuildDelete,
    ChannelCreate,
    ChannelUpdate,
    ChannelDelete,
    ChannelPinsUpdate,
    MessageCreate,
    MessageUpdate,
    MessageDelete,
    MessageDeleteBulk,
    MessagePollVoteAdd,
    MessagePollVoteRemove,
    GuildMemberAdd,
    GuildMemberUpdate,
    GuildMemberRemove,
    GuildMembersChunk,
    MessageReactionAdd,
    MessageReactionRemove,
    MessageReactionRemoveAll,
    MessageReactionRemoveEmoji,
    InteractionCreate,
    UserUpdate,
    PresenceUpdate,
    TypingStart,
    VoiceStateUpdate,
    VoiceServerUpdate,
    VoiceChannelEffectSend,
    WebhooksUpdate,
    InviteCreate,
    InviteDelete,
    GuildBanAdd,
    GuildBanRemove,
    GuildRoleCreate,
    GuildRoleUpdate,
    GuildRoleDelete,
    GuildEmojisUpdate,
    GuildStickersUpdate,
    GuildIntegrationsUpdate,
    GuildAuditLogEntryCreate,
    AutoModerationRuleCreate,
    AutoModerationRuleUpdate,
    AutoModerationRuleDelete,
    AutoModerationActionExecution,
    ApplicationCommandPermissionsUpdate,
    EntitlementCreate,
    EntitlementUpdate,
    EntitlementDelete,
    SubscriptionCreate,
    SubscriptionUpdate,
    SubscriptionDelete,
    GuildScheduledEventCreate,
    GuildScheduledEventUpdate,
    GuildScheduledEventDelete,
    GuildScheduledEventUserAdd,
    GuildScheduledEventUserRemove,
    GuildSoundboardSoundCreate,
    GuildSoundboardSoundUpdate,
    GuildSoundboardSoundDelete,
    GuildSoundboardSoundsUpdate,
    StageInstanceCreate,
    StageInstanceUpdate,
    StageInstanceDelete,
    ThreadCreate,
    ThreadUpdate,
    ThreadDelete,
    ThreadListSync,
    ThreadMembersUpdate,
    ThreadMemberUpdate,
};

pub fn fromEvents(e: Events) Type {
    return switch (e) {
        .ClientReady => .ready,
        .Resumed => .resumed,
        .GuildCreate => .guild_create,
        .GuildUpdate => .guild_update,
        .GuildDelete => .guild_delete,
        .ChannelCreate => .channel_create,
        .ChannelUpdate => .channel_update,
        .ChannelDelete => .channel_delete,
        .ChannelPinsUpdate => .channel_pins_update,
        .MessageCreate => .message_create,
        .MessageUpdate => .message_update,
        .MessageDelete => .message_delete,
        .MessageDeleteBulk => .message_delete_bulk,
        .MessagePollVoteAdd => .message_poll_vote_add,
        .MessagePollVoteRemove => .message_poll_vote_remove,
        .GuildMemberAdd => .guild_member_add,
        .GuildMemberUpdate => .guild_member_update,
        .GuildMemberRemove => .guild_member_remove,
        .GuildMembersChunk => .guild_members_chunk,
        .MessageReactionAdd => .message_reaction_add,
        .MessageReactionRemove => .message_reaction_remove,
        .MessageReactionRemoveAll => .message_reaction_remove_all,
        .MessageReactionRemoveEmoji => .message_reaction_remove_emoji,
        .InteractionCreate => .interaction_create,
        .UserUpdate => .user_update,
        .PresenceUpdate => .presence_update,
        .TypingStart => .typing_start,
        .VoiceStateUpdate => .voice_state_update,
        .VoiceServerUpdate => .voice_server_update,
        .VoiceChannelEffectSend => .voice_channel_effect_send,
        .WebhooksUpdate => .webhooks_update,
        .InviteCreate => .invite_create,
        .InviteDelete => .invite_delete,
        .GuildBanAdd => .guild_ban_add,
        .GuildBanRemove => .guild_ban_remove,
        .GuildRoleCreate => .guild_role_create,
        .GuildRoleUpdate => .guild_role_update,
        .GuildRoleDelete => .guild_role_delete,
        .GuildEmojisUpdate => .guild_emojis_update,
        .GuildStickersUpdate => .guild_stickers_update,
        .GuildIntegrationsUpdate => .guild_integrations_update,
        .GuildAuditLogEntryCreate => .guild_audit_log_entry_create,
        .AutoModerationRuleCreate => .auto_moderation_rule_create,
        .AutoModerationRuleUpdate => .auto_moderation_rule_update,
        .AutoModerationRuleDelete => .auto_moderation_rule_delete,
        .AutoModerationActionExecution => .auto_moderation_action_execution,
        .ApplicationCommandPermissionsUpdate => .application_command_permissions_update,
        .EntitlementCreate => .entitlement_create,
        .EntitlementUpdate => .entitlement_update,
        .EntitlementDelete => .entitlement_delete,
        .SubscriptionCreate => .subscription_create,
        .SubscriptionUpdate => .subscription_update,
        .SubscriptionDelete => .subscription_delete,
        .GuildScheduledEventCreate => .guild_scheduled_event_create,
        .GuildScheduledEventUpdate => .guild_scheduled_event_update,
        .GuildScheduledEventDelete => .guild_scheduled_event_delete,
        .GuildScheduledEventUserAdd => .guild_scheduled_event_user_add,
        .GuildScheduledEventUserRemove => .guild_scheduled_event_user_remove,
        .GuildSoundboardSoundCreate => .guild_soundboard_sound_create,
        .GuildSoundboardSoundUpdate => .guild_soundboard_sound_update,
        .GuildSoundboardSoundDelete => .guild_soundboard_sound_delete,
        .GuildSoundboardSoundsUpdate => .guild_soundboard_sounds_update,
        .StageInstanceCreate => .stage_instance_create,
        .StageInstanceUpdate => .stage_instance_update,
        .StageInstanceDelete => .stage_instance_delete,
        .ThreadCreate => .thread_create,
        .ThreadUpdate => .thread_update,
        .ThreadDelete => .thread_delete,
        .ThreadListSync => .thread_list_sync,
        .ThreadMembersUpdate => .thread_members_update,
        .ThreadMemberUpdate => .thread_member_update,
    };
}

pub const MessageDelete = struct {
    id: []const u8 = "",
    channel_id: []const u8 = "",
    guild_id: ?[]const u8 = null,
};

pub const GuildMemberRemove = struct {
    guild_id: []const u8 = "",
    user: UserRef = .{},

    pub const UserRef = struct {
        id: []const u8 = "",
    };
};

pub const RoleDelete = struct {
    guild_id: []const u8 = "",
    role_id: []const u8 = "",
};

pub fn Payload(comptime t: Type) type {
    return switch (t) {
        .message_create, .message_update => schema.Message,
        .message_delete => MessageDelete,
        .guild_member_add, .guild_member_update => schema.GuildMember,
        .guild_member_remove => GuildMemberRemove,
        .guild_members_chunk => schema.GuildMembersChunk,
        .message_reaction_add, .message_reaction_remove => schema.MessageReaction,
        .message_reaction_remove_all => schema.ReactionRemoveAll,
        .message_reaction_remove_emoji => schema.ReactionRemoveEmoji,
        .guild_ban_add, .guild_ban_remove => schema.GuildBan,
        .guild_role_create, .guild_role_update => schema.Role,
        .guild_role_delete => RoleDelete,
        .typing_start => schema.TypingStart,
        .presence_update => schema.Presence,
        .voice_state_update => schema.VoiceState,
        .voice_server_update => schema.VoiceServerUpdate,
        .webhooks_update => schema.WebhooksUpdate,
        .ready => schema.Ready,
        .resumed => void,
        .channel_create, .channel_update, .channel_delete => schema.Channel,
        .interaction_create => schema.Interaction,
        .message_poll_vote_add, .message_poll_vote_remove => schema.MessagePollVote,
        .entitlement_create, .entitlement_update, .entitlement_delete => schema.Entitlement,
        else => std.json.Value,
    };
}

const event_names = std.StaticStringMap(Type).initComptime(.{
    .{ "READY", .ready },
    .{ "RESUMED", .resumed },
    .{ "GUILD_CREATE", .guild_create },
    .{ "GUILD_UPDATE", .guild_update },
    .{ "GUILD_DELETE", .guild_delete },
    .{ "CHANNEL_CREATE", .channel_create },
    .{ "CHANNEL_UPDATE", .channel_update },
    .{ "CHANNEL_DELETE", .channel_delete },
    .{ "CHANNEL_PINS_UPDATE", .channel_pins_update },
    .{ "MESSAGE_CREATE", .message_create },
    .{ "MESSAGE_UPDATE", .message_update },
    .{ "MESSAGE_DELETE", .message_delete },
    .{ "MESSAGE_DELETE_BULK", .message_delete_bulk },
    .{ "MESSAGE_POLL_VOTE_ADD", .message_poll_vote_add },
    .{ "MESSAGE_POLL_VOTE_REMOVE", .message_poll_vote_remove },
    .{ "GUILD_MEMBER_ADD", .guild_member_add },
    .{ "GUILD_MEMBER_UPDATE", .guild_member_update },
    .{ "GUILD_MEMBER_REMOVE", .guild_member_remove },
    .{ "GUILD_MEMBERS_CHUNK", .guild_members_chunk },
    .{ "MESSAGE_REACTION_ADD", .message_reaction_add },
    .{ "MESSAGE_REACTION_REMOVE", .message_reaction_remove },
    .{ "MESSAGE_REACTION_REMOVE_ALL", .message_reaction_remove_all },
    .{ "MESSAGE_REACTION_REMOVE_EMOJI", .message_reaction_remove_emoji },
    .{ "INTERACTION_CREATE", .interaction_create },
    .{ "USER_UPDATE", .user_update },
    .{ "PRESENCE_UPDATE", .presence_update },
    .{ "TYPING_START", .typing_start },
    .{ "VOICE_STATE_UPDATE", .voice_state_update },
    .{ "VOICE_SERVER_UPDATE", .voice_server_update },
    .{ "VOICE_CHANNEL_EFFECT_SEND", .voice_channel_effect_send },
    .{ "WEBHOOKS_UPDATE", .webhooks_update },
    .{ "INVITE_CREATE", .invite_create },
    .{ "INVITE_DELETE", .invite_delete },
    .{ "GUILD_BAN_ADD", .guild_ban_add },
    .{ "GUILD_BAN_REMOVE", .guild_ban_remove },
    .{ "GUILD_ROLE_CREATE", .guild_role_create },
    .{ "GUILD_ROLE_UPDATE", .guild_role_update },
    .{ "GUILD_ROLE_DELETE", .guild_role_delete },
    .{ "GUILD_EMOJIS_UPDATE", .guild_emojis_update },
    .{ "GUILD_STICKERS_UPDATE", .guild_stickers_update },
    .{ "GUILD_INTEGRATIONS_UPDATE", .guild_integrations_update },
    .{ "GUILD_AUDIT_LOG_ENTRY_CREATE", .guild_audit_log_entry_create },
    .{ "AUTO_MODERATION_RULE_CREATE", .auto_moderation_rule_create },
    .{ "AUTO_MODERATION_RULE_UPDATE", .auto_moderation_rule_update },
    .{ "AUTO_MODERATION_RULE_DELETE", .auto_moderation_rule_delete },
    .{ "AUTO_MODERATION_ACTION_EXECUTION", .auto_moderation_action_execution },
    .{ "APPLICATION_COMMAND_PERMISSIONS_UPDATE", .application_command_permissions_update },
    .{ "ENTITLEMENT_CREATE", .entitlement_create },
    .{ "ENTITLEMENT_UPDATE", .entitlement_update },
    .{ "ENTITLEMENT_DELETE", .entitlement_delete },
    .{ "SUBSCRIPTION_CREATE", .subscription_create },
    .{ "SUBSCRIPTION_UPDATE", .subscription_update },
    .{ "SUBSCRIPTION_DELETE", .subscription_delete },
    .{ "GUILD_SCHEDULED_EVENT_CREATE", .guild_scheduled_event_create },
    .{ "GUILD_SCHEDULED_EVENT_UPDATE", .guild_scheduled_event_update },
    .{ "GUILD_SCHEDULED_EVENT_DELETE", .guild_scheduled_event_delete },
    .{ "GUILD_SCHEDULED_EVENT_USER_ADD", .guild_scheduled_event_user_add },
    .{ "GUILD_SCHEDULED_EVENT_USER_REMOVE", .guild_scheduled_event_user_remove },
    .{ "GUILD_SOUNDBOARD_SOUND_CREATE", .guild_soundboard_sound_create },
    .{ "GUILD_SOUNDBOARD_SOUND_UPDATE", .guild_soundboard_sound_update },
    .{ "GUILD_SOUNDBOARD_SOUND_DELETE", .guild_soundboard_sound_delete },
    .{ "GUILD_SOUNDBOARD_SOUNDS_UPDATE", .guild_soundboard_sounds_update },
    .{ "STAGE_INSTANCE_CREATE", .stage_instance_create },
    .{ "STAGE_INSTANCE_UPDATE", .stage_instance_update },
    .{ "STAGE_INSTANCE_DELETE", .stage_instance_delete },
    .{ "THREAD_CREATE", .thread_create },
    .{ "THREAD_UPDATE", .thread_update },
    .{ "THREAD_DELETE", .thread_delete },
    .{ "THREAD_LIST_SYNC", .thread_list_sync },
    .{ "THREAD_MEMBERS_UPDATE", .thread_members_update },
    .{ "THREAD_MEMBER_UPDATE", .thread_member_update },
});

pub fn classify(t: ?[]const u8) Type {
    const name = t orelse return .unknown;
    return event_names.get(name) orelse .unknown;
}

pub fn discordName(t: Type) []const u8 {
    return switch (t) {
        .ready => "clientReady",
        .resumed => "resumed",
        .guild_create => "guildCreate",
        .guild_update => "guildUpdate",
        .guild_delete => "guildDelete",
        .channel_create => "channelCreate",
        .channel_update => "channelUpdate",
        .channel_delete => "channelDelete",
        .channel_pins_update => "channelPinsUpdate",
        .message_create => "messageCreate",
        .message_update => "messageUpdate",
        .message_delete => "messageDelete",
        .message_delete_bulk => "messageDeleteBulk",
        .message_poll_vote_add => "messagePollVoteAdd",
        .message_poll_vote_remove => "messagePollVoteRemove",
        .guild_member_add => "guildMemberAdd",
        .guild_member_update => "guildMemberUpdate",
        .guild_member_remove => "guildMemberRemove",
        .guild_members_chunk => "guildMembersChunk",
        .message_reaction_add => "messageReactionAdd",
        .message_reaction_remove => "messageReactionRemove",
        .message_reaction_remove_all => "messageReactionRemoveAll",
        .message_reaction_remove_emoji => "messageReactionRemoveEmoji",
        .interaction_create => "interactionCreate",
        .user_update => "userUpdate",
        .presence_update => "presenceUpdate",
        .typing_start => "typingStart",
        .voice_state_update => "voiceStateUpdate",
        .voice_server_update => "voiceServerUpdate",
        .voice_channel_effect_send => "voiceChannelEffectSend",
        .webhooks_update => "webhooksUpdate",
        .invite_create => "inviteCreate",
        .invite_delete => "inviteDelete",
        .guild_ban_add => "guildBanAdd",
        .guild_ban_remove => "guildBanRemove",
        .guild_role_create => "roleCreate",
        .guild_role_update => "roleUpdate",
        .guild_role_delete => "roleDelete",
        .guild_emojis_update => "guildEmojisUpdate",
        .guild_stickers_update => "guildStickersUpdate",
        .guild_integrations_update => "guildIntegrationsUpdate",
        .guild_audit_log_entry_create => "guildAuditLogEntryCreate",
        .auto_moderation_rule_create => "autoModerationRuleCreate",
        .auto_moderation_rule_update => "autoModerationRuleUpdate",
        .auto_moderation_rule_delete => "autoModerationRuleDelete",
        .auto_moderation_action_execution => "autoModerationActionExecution",
        .application_command_permissions_update => "applicationCommandPermissionsUpdate",
        .entitlement_create => "entitlementCreate",
        .entitlement_update => "entitlementUpdate",
        .entitlement_delete => "entitlementDelete",
        .subscription_create => "subscriptionCreate",
        .subscription_update => "subscriptionUpdate",
        .subscription_delete => "subscriptionDelete",
        .guild_scheduled_event_create => "guildScheduledEventCreate",
        .guild_scheduled_event_update => "guildScheduledEventUpdate",
        .guild_scheduled_event_delete => "guildScheduledEventDelete",
        .guild_scheduled_event_user_add => "guildScheduledEventUserAdd",
        .guild_scheduled_event_user_remove => "guildScheduledEventUserRemove",
        .guild_soundboard_sound_create => "guildSoundboardSoundCreate",
        .guild_soundboard_sound_update => "guildSoundboardSoundUpdate",
        .guild_soundboard_sound_delete => "guildSoundboardSoundDelete",
        .guild_soundboard_sounds_update => "guildSoundboardSoundsUpdate",
        .stage_instance_create => "stageInstanceCreate",
        .stage_instance_update => "stageInstanceUpdate",
        .stage_instance_delete => "stageInstanceDelete",
        .thread_create => "threadCreate",
        .thread_update => "threadUpdate",
        .thread_delete => "threadDelete",
        .thread_list_sync => "threadListSync",
        .thread_members_update => "threadMembersUpdate",
        .thread_member_update => "threadMemberUpdate",
        .unknown => "unknown",
    };
}

pub fn normalize(comptime ev: anytype) Type {
    if (@TypeOf(ev) == Type) return ev;
    if (@TypeOf(ev) == Events) return fromEvents(ev);
    if (@typeInfo(@TypeOf(ev)) == .enum_literal) {
        const t: Type = ev;
        return t;
    }
    const name: []const u8 = ev;
    return @field(Names{}, name);
}

const Names = struct {
    ready: Type = .ready,
    clientReady: Type = .ready,
    resumed: Type = .resumed,
    guild_create: Type = .guild_create,
    guildCreate: Type = .guild_create,
    guild_update: Type = .guild_update,
    guildUpdate: Type = .guild_update,
    guild_delete: Type = .guild_delete,
    guildDelete: Type = .guild_delete,
    channel_create: Type = .channel_create,
    channelCreate: Type = .channel_create,
    channel_update: Type = .channel_update,
    channelUpdate: Type = .channel_update,
    channel_delete: Type = .channel_delete,
    channelDelete: Type = .channel_delete,
    channel_pins_update: Type = .channel_pins_update,
    channelPinsUpdate: Type = .channel_pins_update,
    message_create: Type = .message_create,
    messageCreate: Type = .message_create,
    message_update: Type = .message_update,
    messageUpdate: Type = .message_update,
    message_delete: Type = .message_delete,
    messageDelete: Type = .message_delete,
    message_delete_bulk: Type = .message_delete_bulk,
    messageDeleteBulk: Type = .message_delete_bulk,
    message_poll_vote_add: Type = .message_poll_vote_add,
    messagePollVoteAdd: Type = .message_poll_vote_add,
    message_poll_vote_remove: Type = .message_poll_vote_remove,
    messagePollVoteRemove: Type = .message_poll_vote_remove,
    guild_member_add: Type = .guild_member_add,
    guildMemberAdd: Type = .guild_member_add,
    guild_member_update: Type = .guild_member_update,
    guildMemberUpdate: Type = .guild_member_update,
    guild_member_remove: Type = .guild_member_remove,
    guildMemberRemove: Type = .guild_member_remove,
    guild_members_chunk: Type = .guild_members_chunk,
    guildMembersChunk: Type = .guild_members_chunk,
    message_reaction_add: Type = .message_reaction_add,
    messageReactionAdd: Type = .message_reaction_add,
    message_reaction_remove: Type = .message_reaction_remove,
    messageReactionRemove: Type = .message_reaction_remove,
    message_reaction_remove_all: Type = .message_reaction_remove_all,
    messageReactionRemoveAll: Type = .message_reaction_remove_all,
    message_reaction_remove_emoji: Type = .message_reaction_remove_emoji,
    messageReactionRemoveEmoji: Type = .message_reaction_remove_emoji,
    interaction_create: Type = .interaction_create,
    interactionCreate: Type = .interaction_create,
    user_update: Type = .user_update,
    userUpdate: Type = .user_update,
    presence_update: Type = .presence_update,
    presenceUpdate: Type = .presence_update,
    typing_start: Type = .typing_start,
    typingStart: Type = .typing_start,
    voice_state_update: Type = .voice_state_update,
    voiceStateUpdate: Type = .voice_state_update,
    voice_server_update: Type = .voice_server_update,
    voiceServerUpdate: Type = .voice_server_update,
    voice_channel_effect_send: Type = .voice_channel_effect_send,
    voiceChannelEffectSend: Type = .voice_channel_effect_send,
    webhooks_update: Type = .webhooks_update,
    webhooksUpdate: Type = .webhooks_update,
    invite_create: Type = .invite_create,
    inviteCreate: Type = .invite_create,
    invite_delete: Type = .invite_delete,
    inviteDelete: Type = .invite_delete,
    guild_ban_add: Type = .guild_ban_add,
    guildBanAdd: Type = .guild_ban_add,
    guild_ban_remove: Type = .guild_ban_remove,
    guildBanRemove: Type = .guild_ban_remove,
    guild_role_create: Type = .guild_role_create,
    roleCreate: Type = .guild_role_create,
    guild_role_update: Type = .guild_role_update,
    roleUpdate: Type = .guild_role_update,
    guild_role_delete: Type = .guild_role_delete,
    roleDelete: Type = .guild_role_delete,
    guild_emojis_update: Type = .guild_emojis_update,
    guildEmojisUpdate: Type = .guild_emojis_update,
    guild_stickers_update: Type = .guild_stickers_update,
    guildStickersUpdate: Type = .guild_stickers_update,
    guild_integrations_update: Type = .guild_integrations_update,
    guildIntegrationsUpdate: Type = .guild_integrations_update,
    guild_audit_log_entry_create: Type = .guild_audit_log_entry_create,
    guildAuditLogEntryCreate: Type = .guild_audit_log_entry_create,
    auto_moderation_rule_create: Type = .auto_moderation_rule_create,
    autoModerationRuleCreate: Type = .auto_moderation_rule_create,
    auto_moderation_rule_update: Type = .auto_moderation_rule_update,
    autoModerationRuleUpdate: Type = .auto_moderation_rule_update,
    auto_moderation_rule_delete: Type = .auto_moderation_rule_delete,
    autoModerationRuleDelete: Type = .auto_moderation_rule_delete,
    auto_moderation_action_execution: Type = .auto_moderation_action_execution,
    autoModerationActionExecution: Type = .auto_moderation_action_execution,
    application_command_permissions_update: Type = .application_command_permissions_update,
    applicationCommandPermissionsUpdate: Type = .application_command_permissions_update,
    entitlement_create: Type = .entitlement_create,
    entitlementCreate: Type = .entitlement_create,
    entitlement_update: Type = .entitlement_update,
    entitlementUpdate: Type = .entitlement_update,
    entitlement_delete: Type = .entitlement_delete,
    entitlementDelete: Type = .entitlement_delete,
    subscription_create: Type = .subscription_create,
    subscriptionCreate: Type = .subscription_create,
    subscription_update: Type = .subscription_update,
    subscriptionUpdate: Type = .subscription_update,
    subscription_delete: Type = .subscription_delete,
    subscriptionDelete: Type = .subscription_delete,
    guild_scheduled_event_create: Type = .guild_scheduled_event_create,
    guildScheduledEventCreate: Type = .guild_scheduled_event_create,
    guild_scheduled_event_update: Type = .guild_scheduled_event_update,
    guildScheduledEventUpdate: Type = .guild_scheduled_event_update,
    guild_scheduled_event_delete: Type = .guild_scheduled_event_delete,
    guildScheduledEventDelete: Type = .guild_scheduled_event_delete,
    guild_scheduled_event_user_add: Type = .guild_scheduled_event_user_add,
    guildScheduledEventUserAdd: Type = .guild_scheduled_event_user_add,
    guild_scheduled_event_user_remove: Type = .guild_scheduled_event_user_remove,
    guildScheduledEventUserRemove: Type = .guild_scheduled_event_user_remove,
    guild_soundboard_sound_create: Type = .guild_soundboard_sound_create,
    guildSoundboardSoundCreate: Type = .guild_soundboard_sound_create,
    guild_soundboard_sound_update: Type = .guild_soundboard_sound_update,
    guildSoundboardSoundUpdate: Type = .guild_soundboard_sound_update,
    guild_soundboard_sound_delete: Type = .guild_soundboard_sound_delete,
    guildSoundboardSoundDelete: Type = .guild_soundboard_sound_delete,
    guild_soundboard_sounds_update: Type = .guild_soundboard_sounds_update,
    guildSoundboardSoundsUpdate: Type = .guild_soundboard_sounds_update,
    stage_instance_create: Type = .stage_instance_create,
    stageInstanceCreate: Type = .stage_instance_create,
    stage_instance_update: Type = .stage_instance_update,
    stageInstanceUpdate: Type = .stage_instance_update,
    stage_instance_delete: Type = .stage_instance_delete,
    stageInstanceDelete: Type = .stage_instance_delete,
    thread_create: Type = .thread_create,
    threadCreate: Type = .thread_create,
    thread_update: Type = .thread_update,
    threadUpdate: Type = .thread_update,
    thread_delete: Type = .thread_delete,
    threadDelete: Type = .thread_delete,
    thread_list_sync: Type = .thread_list_sync,
    threadListSync: Type = .thread_list_sync,
    thread_members_update: Type = .thread_members_update,
    threadMembersUpdate: Type = .thread_members_update,
    thread_member_update: Type = .thread_member_update,
    threadMemberUpdate: Type = .thread_member_update,
    unknown: Type = .unknown,
};
